### ISSUE TITLE
Argoverse 2

### ISSUE THREAD

**Issue by Cram3r95** [sshaoshuai/MTR#10]
Is this code prepared to run in Argoverse2?

**Comment by Cram3r95** [comment]
Actually Argoverse2 is bigger and better than Waymo:

![imagen](https://user-images.githubusercontent.com/15740838/222124254-f8e8608f-168d-4f5e-a169-b09f43ecdb39.png)

Ok, thank you so much @sshaoshuai, I will try to adapt the code.

**Comment by sshaoshuai** [comment]
It seems that the dataset of waymo motion prediction is much larger than other datasets, and I think it may provide more information than other datasets (e.g., more detailed HDMap). You can try both and see which one you prefer.

**Comment by Cram3r95** [comment]
Ok, I will try, quite sure Argoverse2 has a more detailed HD info.

**Comment by sshaoshuai** [comment]
Feel free to reopen it if there are further questions.

**Comment by ares89** [comment]
@Cram3r95 Have you migrated to argoverse2 yet?

**Comment by Cram3r95** [comment]
@ares89 not with this algorithm, but it is easy to adapt the graph from Argo1 to Argo2 format
