### ISSUE TITLE
ValueError when decoding map features

### ISSUE THREAD

**Issue by Longzhong-Lin** [sshaoshuai/MTR#11]
Is it normal to see the ValueError when decoding map features, or this means that the dataset I've downloaded is broken?

**Comment by sshaoshuai** [comment]
I do not think it is normal. Maybe you can provide more context information or just try to download it again.

**Comment by Longzhong-Lin** [comment]
When I run the preprocess code, data with only id is printed and ValueError will be throught, as in the figure.
![image](https://user-images.githubusercontent.com/81036197/222152191-7c3f457a-1fcd-4534-81c2-86140cb644b8.png)
![image](https://user-images.githubusercontent.com/81036197/222152699-f1bf7c84-72c8-434d-9333-1ca29364624c.png)

**Comment by Longzhong-Lin** [comment]
When I printed all the map data being processed, I saw there are some map segments belong to type "lane".

**Comment by sshaoshuai** [comment]
I haven't met this error - I have tested the codes in the latest dataset - maybe you can try to download the latest dataset.

**Comment by Longzhong-Lin** [comment]
OK, thx for quick reply!

**Comment by kangmiao15** [comment]
> When I run the preprocess code, data with only id is printed and ValueError will be throught, as in the figure. ![image](https://user-images.githubusercontent.com/81036197/222152191-7c3f457a-1fcd-4534-81c2-86140cb644b8.png) ![image](https://user-images.githubusercontent.com/81036197/222152699-f1bf7c84-72c8-434d-9333-1ca29364624c.png)

I also met the same problem. How did you solve it?
