### ISSUE TITLE
dynamic_map_infos

### ISSUE THREAD

**Issue by Zhanwei-Z** [sshaoshuai/MTR#12]
Hi, @sshaoshuai  Thanks for your awesome work!
I wonder why the features of dynamic_map_infos in original pkl files are  not extracted in waymo_dataset.py? It seems they are also useful.

**Comment by sshaoshuai** [comment]
I just found that the framework can already achieve good performance without using dynamic map infos, but I agree that this information is also very useful. But how to effectively incorporate this information into the framework should be explored.
