### ISSUE TITLE
question about motion query pair initialization

### ISSUE THREAD

**Issue by Apocalypse2403** [sshaoshuai/MTR#15]
Dear author, thanks for your excellent work and code release! I have read your paper and there is a question about motion query 
pair initialization. In this work. I notice that the intention points are generated by adopting k-means clustering algorithm on the endpoints of **GT** trajectorys and are used to initialize the motion query pair and predicted trajectories in the 1st layer of decoder. I'm confused that how to initialize the query pair and trajectories during the inference because there is no GT in this phase.

**Comment by sshaoshuai** [comment]
The intention points are just generated on training data, and then in the testing time, the intention points can be considered as some fixed parameters and do not need to be generated online.
