### ISSUE TITLE
KNN_CUDA

### ISSUE THREAD

**Issue by 76qian** [sshaoshuai/MTR#17]
Hello, I'm glad to see your code. But I encountered some problems in the implementation process. I cannot import KNN_ CUDA after successful compilation, I have searched the relevant information online but haven't solved it. I hope you can help me solve this problem. Thank you very much and look forward to your reply!
![2023-03-15 13-04-11 的屏幕截图(1)](https://user-images.githubusercontent.com/96508781/225213634-58311454-9f7a-426b-a82b-e777beadbe66.png)

**Comment by sshaoshuai** [comment]
Can you provide more error information to help debug the problem?

**Comment by 76qian** [comment]
Hello, thank you very much for your reply. In fact, I have encountered difficulties downloading datasets and have not started processing data and training, just in the preparation phase of the environment. This error may be an environmental issue because I don't think future data processing and operation will work against this error.
About knn_ Cuda's Error: Not Only Knon Reported an Error_ Cuda, and there's an attention_ cuda.
I hope you can give me some suggestions, thank you very much!
<img width="188" alt="0de40eddf5fec39990b38337282f5b9" src="https://user-images.githubusercontent.com/96508781/226229249-ee9ace63-fd61-4af7-be21-b028840a22b1.png">

**Comment by sshaoshuai** [comment]
I think it may just relate to your IDE and it is not an error. You can try to run it and see whether it is ok.
