### ISSUE TITLE
why is the top1 metric very bad ?

### ISSUE THREAD

**Issue by danpanwan** [sshaoshuai/MTR#19]
when i train the model, i found that the top6 metric (minADE, minFDE and so on) is good, but the top1 (sorted by probability) metric is very bad. It seems that the classification between multi output trajectories is very hard to learn. Have you noticed this phenomenon ?  And do you have any idea to resolve it ? I am looking forward to your reply.

**Comment by sshaoshuai** [comment]
I didn't test with the top1 metric on waymo dataset, but it is quite normal that top 1 metric is bad than top 6 as top 6 has more predicted trajectories.

**Comment by danpanwan** [comment]
The top1 metric is about two times of the top6 metric. In practical application scenarios，the top1 trajectory is very important. I am curious about how can i promote the top1 performance.

**Comment by sshaoshuai** [comment]
That's a good research question. 

BTW, Argoverse2 has the evaluation of both top 1 and top 6: 
https://eval.ai/web/challenges/challenge-page/1719/leaderboard/4098
where we can notice that the top1 errors are generally more than two times than the top6 errors for all methods.
