### ISSUE TITLE
what is dense future prediction

### ISSUE THREAD

**Issue by lon0862** [sshaoshuai/MTR#2]
Excuse me, I see there is a dense future prediction after transformer encoder.But I don't see any description in paper to discuss about it. Can you explain what "Dense Future Prediction" is?

**Comment by sshaoshuai** [comment]
Please refer to the final paragraph of Section 3.1 in our formal paper: https://arxiv.org/pdf/2209.13508.pdf

**Comment by lon0862** [comment]
OK thanks, I dont mention that you update the paper
