### ISSUE TITLE
About the intention point file.

### ISSUE THREAD

**Issue by Dylan-LDR** [sshaoshuai/MTR#20]
Dear Author,
Thanks for your great work. When do training, a bug is reported as "No file 'cluster_64_center_dict.pkl'". I wonder where I can find it or should we generate the intention point file by some commands? Looking forward to your reply.

**Comment by sshaoshuai** [comment]
You can find the file here: https://github.com/sshaoshuai/MTR/tree/master/data/waymo

**Comment by Dylan-LDR** [comment]
Oh, I see. I deleted it by mistake when doing data preprocessing. Really thanks for the kind reply.
