### ISSUE TITLE
Error while runnung train.py

### ISSUE THREAD

**Issue by febinfredi** [sshaoshuai/MTR#22]
Hi, when I'm running the command `bash scripts/dist_train.sh 8 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 80 --epochs 30 --extra_tag my_first_exp`, I'm getting the following error:

```
+ NGPUS=8
+ PY_ARGS='--cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 30 --epochs 100 --extra_tag my_first_exp'
+ true
+ PORT=10808
++ nc -z 127.0.0.1 10808
++ echo 1
+ status=1
+ '[' 1 '!=' 0 ']'
+ break
+ echo 10808
10808
+ python -m torch.distributed.launch --nproc_per_node=8 --rdzv_endpoint=localhost:10808 train.py --launcher pytorch --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 30 --epochs 100 --extra_tag my_first_exp
/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions
  warnings.warn(
WARNING:torch.distributed.run:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 

usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=0
train.py: error: unrecognized arguments: --local-rank=2
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=3
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=6
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=7
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=1
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=5
usage: train.py [-h] [--cfg_file CFG_FILE] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT] [--pretrained_model PRETRAINED_MODEL]
                [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT] [--without_sync_bn] [--fix_random_seed] [--ckpt_save_interval CKPT_SAVE_INTERVAL] [--local_rank LOCAL_RANK]
                [--max_ckpt_save_num MAX_CKPT_SAVE_NUM] [--merge_all_iters_to_one_epoch] [--set ...] [--max_waiting_mins MAX_WAITING_MINS] [--start_epoch START_EPOCH] [--save_to_file] [--not_eval_with_train]
                [--logger_iter_interval LOGGER_ITER_INTERVAL] [--ckpt_save_time_interval CKPT_SAVE_TIME_INTERVAL] [--add_worker_init_fn]
train.py: error: unrecognized arguments: --local-rank=4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 10113) of binary: /home/febin/anaconda3/envs/mtr/bin/python
Traceback (most recent call last):
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/febin/anaconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

train.py FAILED

Failures:
[1]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 10114)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 10115)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 10116)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 10117)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 10118)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 10119)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 10120)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2023-03-17_18:49:28
  host      : febin-ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 10113)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
Any help will be appreciated
Thank you

**Comment by sshaoshuai** [comment]
This codebase expects to receive the config of `--local_rank` to specify the GPU index, but your environment provides `--local-rank`. I am not sure what happens, can you provide your PyTorch version? 
To solve it, I guess you can simply add one more new config `--local-rank` and map it to the original `--local_rank`.

**Comment by NIHALNAVALE** [comment]
(mtr) nihal@nihal-Ubuntu:~/MTR/tools$ bash scripts/dist_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 1 --extra_tag my_first_exp
+ NGPUS=1
+ PY_ARGS='--cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 1 --extra_tag my_first_exp'
+ true
+ PORT=21575
++ nc -z 127.0.0.1 21575
++ echo 1
+ status=1
+ '[' 1 '!=' 0 ']'
+ break
+ echo 21575
21575
+ python -m torch.distributed.launch --nproc_per_node=1 --rdzv_endpoint=localhost:21575 train.py --launcher pytorch --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 1 --extra_tag my_first_exp
/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from mtr.models import model as model_utils
  File "/home/nihal/MTR/tools/../mtr/models/model.py", line 12, in <module>
    from .context_encoder import build_context_encoder
  File "/home/nihal/MTR/tools/../mtr/models/context_encoder/__init__.py", line 7, in <module>
    from .mtr_encoder import MTREncoder
  File "/home/nihal/MTR/tools/../mtr/models/context_encoder/mtr_encoder.py", line 12, in <module>
    from mtr.models.utils.transformer import transformer_encoder_layer, position_encoding_utils
  File "/home/nihal/MTR/tools/../mtr/models/utils/transformer/transformer_encoder_layer.py", line 16, in <module>
    from .multi_head_attention_local import MultiheadAttentionLocal
  File "/home/nihal/MTR/tools/../mtr/models/utils/transformer/multi_head_attention_local.py", line 21, in <module>
    from mtr.ops import attention
  File "/home/nihal/MTR/tools/../mtr/ops/attention/__init__.py", line 5, in <module>
    from . import attention_utils
  File "/home/nihal/MTR/tools/../mtr/ops/attention/attention_utils.py", line 9, in <module>
    from . import attention_cuda
ImportError: /home/nihal/MTR/tools/../mtr/ops/attention/attention_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 69882) of binary: /home/nihal/miniconda3/envs/mtr/bin/python
Traceback (most recent call last):
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nihal/miniconda3/envs/mtr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-20_19:54:35
  host      : nihal-Ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 69882)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by febinfredi** [comment]
I have pytorch version 1.13.0 and the error posted above is from my teammate, we both are facing the same issues

**Comment by febinfredi** [comment]
Hi, I was able to solve this error by using torchrun instead of torch.distribution.launch

**Comment by qiyan98** [comment]
> I have pytorch version 1.13.0 and the error posted above is from my teammate, we both are facing the same issues

Same here. I think the default method to run the training should be changed to `torchrun`. :)

**Comment by YoushaaMurhij** [comment]
> Hi, I have the same problem:
> 
> ```shell
> bash scripts/torchrun_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 30 --extra_tag my_first_exp;"
> ```
> 
> Num_of_workers= 8 RAM = 240GB GPU = 32GB
> 
> I tried with multiple gpus and more workers but the same error appears. Any suggestions? @sshaoshuai, @qiyan98, @febinfredi, @NIHALNAVALE Thanks!
> 
> ```shell
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 36) of binary: /usr/bin/python3
> Traceback (most recent call last):
>   File "/usr/local/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 761, in main
>     run(args)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 752, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> train.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> ```

Update: upgrading PyTorch solved the problem for me.

**Comment by ArielleZhang** [comment]
> > Hi, I have the same problem:
> > ```shell
> > bash scripts/torchrun_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 30 --extra_tag my_first_exp;"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Num_of_workers= 8 RAM = 240GB GPU = 32GB
> > I tried with multiple gpus and more workers but the same error appears. Any suggestions? @sshaoshuai, @qiyan98, @febinfredi, @NIHALNAVALE Thanks!
> > ```shell
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 36) of binary: /usr/bin/python3
> > Traceback (most recent call last):
> >   File "/usr/local/bin/torchrun", line 8, in <module>
> >     sys.exit(main())
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
> >     return f(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 761, in main
> >     run(args)
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 752, in run
> >     elastic_launch(
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > ============================================================
> > train.py FAILED
> > ------------------------------------------------------------
> > Failures:
> >   <NO_OTHER_FAILURES>
> > ------------------------------------------------------------
> > ```
> 
> Update: upgrading PyTorch solved the problem for me.

Hi, could you post which pytorch version worked for you? I tried torchrun_train.sh with 1.13.0 and 1.13.1 but they both gave me the same error as you shown. Thanks a lot!

**Comment by febinfredi** [comment]
> > > Hi, I have the same problem:
> > > ```shell
> > > bash scripts/torchrun_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 1 --epochs 30 --extra_tag my_first_exp;"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Num_of_workers= 8 RAM = 240GB GPU = 32GB
> > > I tried with multiple gpus and more workers but the same error appears. Any suggestions? @sshaoshuai, @qiyan98, @febinfredi, @NIHALNAVALE Thanks!
> > > ```shell
> > > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 36) of binary: /usr/bin/python3
> > > Traceback (most recent call last):
> > >   File "/usr/local/bin/torchrun", line 8, in <module>
> > >     sys.exit(main())
> > >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
> > >     return f(*args, **kwargs)
> > >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 761, in main
> > >     run(args)
> > >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 752, in run
> > >     elastic_launch(
> > >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
> > >     return launch_agent(self._config, self._entrypoint, list(args))
> > >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
> > >     raise ChildFailedError(
> > > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > > ============================================================
> > > train.py FAILED
> > > ------------------------------------------------------------
> > > Failures:
> > >   <NO_OTHER_FAILURES>
> > > ------------------------------------------------------------
> > > ```
> > 
> > 
> > Update: upgrading PyTorch solved the problem for me.
> 
> Hi, could you post which pytorch version worked for you? I tried torchrun_train.sh with 1.13.0 and 1.13.1 but they both gave me the same error as you shown. Thanks a lot!

Hi @ArielleZhang, I was using pytorch version 1.13.0
