### ISSUE TITLE
Why use a 12 dimensional embedding to encode timestamp feature?

### ISSUE THREAD

**Issue by liuxy416** [sshaoshuai/MTR#23]
Dear Author,
Thanks for your great work. 

I wonder why you use a 12 dimensional embedding to encode timestamp feature instead of just encode the relative timestamp feature using a 1 dimensional embedding ? Is there any ablation study aimed at this?

**Comment by sshaoshuai** [comment]
Not yet. I prefer to use one-hot embedding, but actually I am not sure which one is better.
