### ISSUE TITLE
waymo dataset version

### ISSUE THREAD

**Issue by Longzhong-Lin** [sshaoshuai/MTR#27]
I see there are multiple version of Waymo Motion Dataset, which one is your choice?
![image](https://user-images.githubusercontent.com/81036197/228769688-5ca13ec4-7055-4d9f-baa5-a1ac192dcdf6.png)

**Comment by sshaoshuai** [comment]
I use the motion dataset of version 1.1, and I think the codes should still work well with version 1.2.

**Comment by twkillian** [comment]
I apologize for not searching the issues prior to posting. I am however having errors with the pre-processing of dataset v1.2 as raised in #83 ...
