### ISSUE TITLE
'CENTER_OFFSET_OF_MAP', (30.0, 0)

### ISSUE THREAD

**Issue by ggosjw** [sshaoshuai/MTR#29]
Hi, I am very impressed by your great open-source work.

I want to ask you how you got the (30,0) for the  center_offset.
center_offset=self.dataset_cfg.get('CENTER_OFFSET_OF_MAP', (30.0, 0)),

Thank you in advance.

**Comment by sshaoshuai** [comment]
This is a hyperparameter and I just set it empirically.

**Comment by ggosjw** [comment]
Got it! 
Thank you for your reply.
