### ISSUE TITLE
Looking Forward to Pretrain Weights

### ISSUE THREAD

**Issue by Longzhong-Lin** [sshaoshuai/MTR#30]
Wonderful work! However, the training on the full dataset seems too resource-consuming, I wonder if you release the pretrained weights of model after?

**Comment by sshaoshuai** [comment]
We can not publish the pretrained models due to the official rules and licenses of [Waymo Open Dataset](https://waymo.com/open/faq/), but you can easily reproduce our performance with our open-source codes.
