### ISSUE TITLE
About Data Normalization

### ISSUE THREAD

**Issue by huyuening** [sshaoshuai/MTR#31]
I found your work only includes "we adopt the agent-centric strategy that normalizes all inputs to the coordinate system centered at this agent", but is it necessary to do further normalization of the input data (track and road map), e.g. min-max, z-score.

**Comment by sshaoshuai** [comment]
Sorry, I didn't try this setting so I can not give a detailed answer to this question. Maybe it will be slightly better.

**Comment by huyuening** [comment]
Thanks for your reply
