### ISSUE TITLE
what's the version of your CUDA toolkit?

### ISSUE THREAD

**Issue by yaqlee** [sshaoshuai/MTR#35]
The CUDA and PyTorch versions I am using are 1.10.1+cu111. I keep encountering the following error after running for a while:

> 
> CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)
> Epoch 0: 0%| | 361/97977 [01:36<7:14:33, 3.74it/s, loss=104, v_num=]
> [W CUDAGuardImpl.h:113] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
> terminate called after throwing an instance of 'c10::CUDAError'
> what(): CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stack trace below might be incorrect.
> For debugging, consider passing CUDA_LAUNCH_BLOCKING=1.
> Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):

These errors always occur in the linear layer of the transformer_encoder_layer. It feels like it's caused by CUDA implementation of attention. What is the CUDA version used in the environment when building the attention operator?

**Comment by sshaoshuai** [comment]
I used cuda 9.2, but I think other CUDA versions should also work since I didn't introduce some complex dependency on the CUDA version.

**Comment by 1zw** [comment]
> The CUDA and PyTorch versions I am using are 1.10.1+cu111. I keep encountering the following error after running for a while:
> 
> > CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)
> > Epoch 0: 0%| | 361/97977 [01:36<7:14:33, 3.74it/s, loss=104, v_num=]
> > [W CUDAGuardImpl.h:113] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
> > terminate called after throwing an instance of 'c10::CUDAError'
> > what(): CUDA error: an illegal memory access was encountered
> > CUDA kernel errors might be asynchronously reported at some other API call, so the stack trace below might be incorrect.
> > For debugging, consider passing CUDA_LAUNCH_BLOCKING=1.
> > Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
> 
> These errors always occur in the linear layer of the transformer_encoder_layer. It feels like it's caused by CUDA implementation of attention. What is the CUDA version used in the environment when building the attention operator?

Sorry to bother you, I wanted to ask if you have solved this problem
