### ISSUE TITLE
The issue in the prediction.

### ISSUE THREAD

**Issue by QC625** [sshaoshuai/MTR#39]
Hello, Thanks for your work！However, I found that many trajectories would experience a U-turn like the one shown in the following figure when I was using MTR to predict trajectories. May I ask what may be the cause of this issue? I understand that MTR involves generating static intent points first, followed by dynamic map collection to refine the trajectory. Can we assume that the target point position is correct, but there is a problem with trajectory generation?
![42](https://github.com/sshaoshuai/MTR/assets/94269942/537a7b77-e571-4eec-bfd6-ea73600a60a0)

**Comment by sshaoshuai** [comment]
No idea why this happens, as previously I didn't notice the visualization carefully. 

Hope to see whether other people also have these unnormal effects.
