### ISSUE TITLE
Does the  ops folder  have a python version

### ISSUE THREAD

**Issue by Tinnk** [sshaoshuai/MTR#40]
Is there a python version of the attention file and the knn file? 
We encountered difficulties when converting to the onnx format. The attentionWeightComputation class cannot be converted. We deduce that because of the use of the C++ file

**Comment by sshaoshuai** [comment]
The current implementation of local attention will indeed bring some difficulties for using ONNX and tensorRT. This local attention actually can also be implemented with native PyTorch, but will also lead to more GPU memory cost.
