### ISSUE TITLE
Code for visualization

### ISSUE THREAD

**Issue by Jaswanth987** [sshaoshuai/MTR#43]
How to visualize , i only have pred_trajs in pickle file , how to visualize that predictions.

**Comment by sshaoshuai** [comment]
I draw the trajectories with matplotlib, and you can also explore this tool by just considering trajectories as connected segments.

**Comment by Jaswanth987** [comment]
Thank you, can you provide sample code for how to draw using matplotlib?

**Comment by Jaswanth987** [comment]
Thank you, I will get only traj with out map info , how to draw trajectories on to map

**Comment by sshaoshuai** [comment]
The map are considered as polylines and can also be drawn with plt.plot.

**Comment by Jaswanth987** [comment]
Thank you, But there will be no map information present in result.pkl file, so how to draw trajectories along with map data . Can you please give sample code for trajectories and map info also.

**Comment by sshaoshuai** [comment]
We did not store the map information on the result.pkl since it just contains the model's output and some important metadata. For drawing the results on the map data, you need to collect the map information from the processed data (please refer to the dataloader to see how to process the map data).
