### ISSUE TITLE
Python setup.py failed

### ISSUE THREAD

**Issue by hadis-h** [sshaoshuai/MTR#44]
I have an issue with installation when I run the command setup.py, it gave me this error :

![photo_2023-06-21 08 28 25](https://github.com/sshaoshuai/MTR/assets/105078009/beacca86-13fc-4618-9e81-f76e5712c54e)

How can I solve this issue?

**Comment by sshaoshuai** [comment]
Can you provide the full log for debugging?

**Comment by kaizhangrtx** [comment]
I have a similar setup error.
![setup1](https://github.com/sshaoshuai/MTR/assets/140166104/4055a9b3-6774-48fd-a3c6-2acc500b6821)
![pythonsetup2](https://github.com/sshaoshuai/MTR/assets/140166104/4f663820-cac8-4a10-bcb0-c0dcf0bfb5ce)
