### ISSUE TITLE
No idea why this happens, as previously I didn't notice the visualization carefully.

### ISSUE THREAD

**Issue by ggosjw** [sshaoshuai/MTR#45]
No idea why this happens, as previously I didn't notice the visualization carefully. 

Hope to see whether other people also have these unnormal effects.

_Originally posted by @sshaoshuai in https://github.com/sshaoshuai/MTR/issues/39#issuecomment-1575495051_

**Comment by ggosjw** [comment]
Thank you for making your fantastic prediction framework available to the public.
While visualizing the MTR prediction outcomes, I encountered a scenario that resembles the aforementioned quoting issue. Initially, the predictions are accurate in the first frame, but they become less stable over time, culminating in a circular trajectory prediction towards the end (as shown in the video).

https://github.com/sshaoshuai/MTR/assets/87901530/f2ca19f4-edba-4285-aef8-eb95ccd37443

Could you possibly offer some guidance or insights into this unusual outcome?
Any wisdom or assistance you can provide would be greatly appreciated. Thank you.

**Comment by jiaxiaosong1002** [comment]
Hi ggosjw,

Your visualization code is great! Could you please provide this snippet so that I could check my output as well? Thanks!

**Comment by ggosjw** [comment]
> Hi ggosjw,
> 
> Your visualization code is great! Could you please provide this snippet so that I could check my output as well? Thanks!

I appreciate your suggestions, but I don't intend to share any visualization code at the moment due to personal reasons. Thank you for your understanding. It primarily involves some work with pyplot.

**Comment by penglo** [comment]
> Hi ggosjw,
> 
> Your visualization code is great! Could you please provide this snippet so that I could check my output as well? Thanks!

“Hi, do you have visualization code for MTR? If so, could you please share it? Thanks in advance.”

**Comment by penglo** [comment]
> > Hi ggosjw,
> > Your visualization code is great! Could you please provide this snippet so that I could check my output as well? Thanks!
> 
> I appreciate your suggestions, but I don't intend to share any visualization code at the moment due to personal reasons. Thank you for your understanding. It primarily involves some work with pyplot.

“Hi, do you have visualization code for MTR? If so, could you please share it? Thanks in advance.”
