### ISSUE TITLE
Is there any plan to release the MTR++ code?

### ISSUE THREAD

**Issue by ShadowLau** [sshaoshuai/MTR#46]
Dear Author,

First, congratulations for winning the Waymo 2023 Motion Prediction Challenge! The improvement of MTR++ is very interesting and effective.

Is there any plan to release the MTR++ code?

Best,

**Comment by sshaoshuai** [comment]
Yes, we plan to release the codes of MTR++, but currently I can not promise a date since its formal paper is still under review.

**Comment by ShadowLau** [comment]
> Yes, we plan to release the codes of MTR++, but currently I can not promise a date since its formal paper is still under review.

That's great! Thank you!

**Comment by Longzhong-Lin** [comment]
> Yes, we plan to release the codes of MTR++, but currently I can not promise a date since its formal paper is still under review.

Cool! I wonder when wiil you release your preprint or technical report?

**Comment by sshaoshuai** [comment]
The formal paper is already released here: https://arxiv.org/abs/2306.17770

**Comment by imean1314** [comment]
Hello, I wonder whether your formal paper review is finished or not. Is there any schedule to release the code of MTR++? Thanks.
