### ISSUE TITLE
Question Regard to Auxilary Task

### ISSUE THREAD

**Issue by SwagJ** [sshaoshuai/MTR#5]
Hi @sshaoshuai, 

Thank you for sharing your great work. I have one question regarding to the auxilary task, more specifically the training process. According to your paper(Eq.3), the auxilary task only predicts single mode trajectory. And dynamic map collection is performed based on  this endpoint of this trajectory. However, during the training, do you still use the endpoint of predicted trajectory as reference center point of dynamic map collection? It would make more sense to use the endpoint of GT during training since it might help stablize training process? 
In addition, for layer0 of transformer decoder, the dynamic searching query is initialized from endpoint auxilary prediction or initializedd from all zeros? 
I am looking forward to your reply. Thank you in advance. 

Best,

**Comment by sshaoshuai** [comment]
Sorry for the late reply as I have been busy with some things recently. 

The dynamic map collection aims to collect trajectory-specific features, so we use the waypoints (including the endpoint) of the predicted trajectory for collecting map features along this trajectory. To be consistent with this dynamic map collection process, we use the positional encoding of the predicted endpoint as the dynamic searching query. We haven't explored whether the endpoint of GT will stabilize the training process. 
However, during training process, we do use the fixed intention points for assigning targets (Sec. 3.3), which is essential to stabilize the training process. 

The layer0 of the transformer decoder, the dynamic searching query is initialized with its corresponding intention points (mentioned in "Local movement refinement" of Sec. 3.2).

**Comment by SwagJ** [comment]
Hi @sshaoshuai,

Thank you for your reply. What I am concerned mainly about is the Y_t in Eq.5. According to the Eq.5, it seems that the dynamic map update only performs once for one level of decoder. Is this true? If not, then the extra question will be what will Y_t at layer0 be? Is this randomly initialized or from the single mode trajectory from auxilary task? I am looking forward to your reply. 
Thank you in advance. 

Best,

**Comment by sshaoshuai** [comment]
Yes, dynamic map update performs once for each level of decoder, and Y_0 at the first decoder layer is initialized as its corresponding intention point I.

**Comment by SwagJ** [comment]
Hi @sshaoshuai,

Thank you for your swift reply. I still have some question regarding to the dynamic map collection. So the dynamic map collection is performed once for every mode k in Y_T, right? Then, what is the shape of alpha(M) in Eq.7, is it still R^(L x D)? If so, the dynamic map collect closest L map polylines with all modes of Y_T? 
I am looking forward to your reply. Thank you very much. 

Best,

**Comment by sshaoshuai** [comment]
The dynamic map collection is performed for each mode separately, so you can consider alpha(M) as KxLxD (each mode has its corresponding L map polylines).

**Comment by SwagJ** [comment]
Thank you very much for your explanation.
