### ISSUE TITLE
只有1个GPU怎么运行该代码

### ISSUE THREAD

**Issue by YangLinger** [sshaoshuai/MTR#52]
您好，我是西南交通大学的学生，在研究轨迹预测方向，看到您的作品非常吸引人，让人眼前一亮。
但是目前受到了阻碍，因为我们实验室的条件只有1个GPU，我尝试把8改为1就会报错，请问有什么方法可以使得该项目只在1个GPU上运行，或您能提供我其他解决方案吗？感谢您提供如此优秀的项目源码，这使我受益匪浅。

**Comment by sshaoshuai** [comment]
For training with single GPU, you can directly run the file train.py as follows: 
python train.py --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 10 --epochs 30 --extra_tag my_first_exp

**Comment by chrisxuxuhui** [comment]
I also want to know only one GPU train waymo data , how long time could train 30 epochs?

**Comment by sshaoshuai** [comment]
For estimating the training time in your own setting, please refer to https://github.com/sshaoshuai/MTR/issues/54.

**Comment by ouyangziyao** [comment]
> 我还想知道只有一个GPU训练waymo数据，需要多长时间才能训练30个epoch？

看了训练时间，是不是一个10g的GPU做不了这种实验？
