### ISSUE TITLE
Asding for params and flops

### ISSUE THREAD

**Issue by FallenMeteorite** [sshaoshuai/MTR#53]
Hello author, I am comparing params and flops of several models in each epoch, but I had a problem when the dataloader was created, I hope you can provide the forecast params and flops in 3 seconds, thank you very much for your help.

**Comment by sshaoshuai** [comment]
MTR model has about 65M parameters, and I can not give an accurate number of flops since there has local attention in MTR model that is related to the number of elements in each scenario.
