### ISSUE TITLE
questions about waymo_prediction_dataset_v1.2

### ISSUE THREAD

**Issue by NaNaoiSong** [sshaoshuai/MTR#60]
Thanks for the great project. 

I see a new type "driveway" added in map_features, which raises `ValueError` in `data_preprocess.py`. To support V1.2, I added it in func `decode_map_features_from_proto`(sry, I failed to add a img). It seems that only polyline are used in model, so will this change make a bad influence on model performance?

**Comment by sshaoshuai** [comment]
I think it may just have little effect on the performance, but I am not quite sure. You can just ignore this new attribute if you have concerns about this.

**Comment by likun97** [comment]
> Thanks for the great project.
> 
> I see a new type "driveway" added in map_features, which raises `ValueError` in `data_preprocess.py`. To support V1.2, I added it in func `decode_map_features_from_proto`(sry, I failed to add a img). It seems that only polyline are used in model, so will this change make a bad influence on model performance?

Hi, I have the same question with you, how do you fix the issue while supporting V1.2.0 in data_preprocess.py ? Thanks!

**Comment by NaNaoiSong** [comment]
> Hi, I have the same question with you, how do you fix the issue while supporting V1.2.0 in data_preprocess.py ? Thanks!

In `waymo_types.py`, 
![image](https://github.com/sshaoshuai/MTR/assets/24368194/dee50470-0955-4de6-b7f6-c348a5db1db2)

In `data_preprocess.py`,
![image](https://github.com/sshaoshuai/MTR/assets/24368194/153ba74a-3375-480d-8042-a916b38500b9)
![image](https://github.com/sshaoshuai/MTR/assets/24368194/7c398da3-acf4-411f-89ed-4fb46caf3fae)
![image](https://github.com/sshaoshuai/MTR/assets/24368194/f0608dab-eaf0-46f5-95d3-aaba9099ae9c)

      elif cur_data.driveway.ByteSize() > 0:
          global_type = polyline_type['TYPE_DRIVEWAY']
          cur_polyline = np.stack([np.array([point.x, point.y, point.z, global_type]) for point in cur_data.driveway.polygon], axis=0)
          cur_polyline_dir = get_polyline_dir(cur_polyline[:, 0:3])
          cur_polyline = np.concatenate((cur_polyline[:, 0:3], cur_polyline_dir, cur_polyline[:, 3:]), axis=-1)
          map_infos['driveway'].append(cur_info)


and the results trained with 20% data are
![image](https://github.com/sshaoshuai/MTR/assets/24368194/74e59e3b-cbda-4eab-a5ea-00dd9cd042f7)
