### ISSUE TITLE
I want to know cyclist pedestrian vehicle share the same network or have own network 

### ISSUE THREAD

**Issue by chrisxuxuhui** [sshaoshuai/MTR#61]
hello,
 I want to know when after training cyclist pedestrian vehicle share the same network or have own network in both encode and decode?

**Comment by sshaoshuai** [comment]
We use the same model for all categories, and you can refer the config here: https://github.com/sshaoshuai/MTR/blob/master/tools/cfgs/waymo/mtr%2B100_percent_data.yaml#L3
