### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by ahsan155** [sshaoshuai/MTR#64]
When I run the training script, I get the error "ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1". Could this be related to gpu? I only have one gpu(RTX 4070ti).
I don't want to go through the long training process. Can you please provide pretrained weights?

**Comment by sshaoshuai** [comment]
For running with a single GPU, please use the command like this: 
`python train.py --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 10 --epochs 30 --extra_tag my_first_exp`. 

The license of waymo open dataset does not allow us release the pre trained weights, please check here https://waymo.com/open/faq/
