### ISSUE TITLE
Starting Training from a Previous Model

### ISSUE THREAD

**Issue by The-Engineer9** [sshaoshuai/MTR#65]
Hi, 

I noticed that you have two parameters that may allow for training starting from a previously trained model (--ckpt and --pretrained_model). I have tried both but I get an error saying that file is not found, using a command that looks like this: "bash scripts/dist_train.sh 1 --cfg_file cfgs/waymo/mtr+100_percent_data.yaml --batch_size 4 --epochs 1 --extra_tag my_second_exp --ckpt /MTR/output/waymo/mtr+100_percent_data/my_first_expe/ckpt/latest_model.pth"

Do you have any advice with regards to what I am doing wrong? Thank you in advance.

**Comment by sshaoshuai** [comment]
It seems that your given path `/MTR/output/waymo/mtr+100_percent_data/my_first_expe/ckpt/latest_model.pth` is not correct. If you are under the folder of MTR/tools, please give correct path like this: `../output/waymo/mtr+100_percent_data/my_first_expe/ckpt/latest_model.pth`
