### ISSUE TITLE
A concern in encoder

### ISSUE THREAD

**Issue by PbTfcLx** [sshaoshuai/MTR#67]
I find that the obj_trajs in mtr encoder without batch_size has 4 dimensions, but call polyline_encoder's forward should use 4 dimensions' tensor with batch_size. Is there any error?

**Comment by sshaoshuai** [comment]
From here , 

https://github.com/sshaoshuai/MTR/blob/a5ba7bdafa09a1a355cc34f8a895499a2b14ddb3/mtr/models/context_encoder/mtr_encoder.py#L166-L167

you can see that the shape of obj_trajs_in is (num_center_objects, num_objects, num_timestamp, C), where the first dimension `num_center_objects` actually already considers the batch size.
