### ISSUE TITLE
Meaning of GMM components ρ

### ISSUE THREAD

**Issue by zhangdongkun98** [sshaoshuai/MTR#71]
Hello!
I noticed that, in Eq. 9 and Eq. 10 of your paper, Gaussian components include 5 parameters (μx, σx, μy, σy, ρ). I would like to know the meaning of ρ, could you provide me with more information or materials about this parameter? It seems that the standard Gaussian component of GMM only contains 4 parameters (μx, σx, μy, σy). I am curious about the role of ρ in a Gaussian component. Thanks very much!

Eq.9:
<img width="877" alt="截屏2023-09-18 19 23 27" src="https://github.com/sshaoshuai/MTR/assets/71307861/b6f424eb-6a04-4cca-97fe-65239861342f">

Eq.10:
<img width="882" alt="截屏2023-09-18 19 23 55" src="https://github.com/sshaoshuai/MTR/assets/71307861/7e1b4451-84cb-44f9-8cc9-819102769d77">

**Comment by sshaoshuai** [comment]
Please refer to the bivariate Gaussian distribution, and it has the $\rho$ as the correlation between two dimensions: 

https://en.wikipedia.org/wiki/Multivariate_normal_distribution

**Comment by zhangdongkun98** [comment]
> Please refer to the bivariate Gaussian distribution, and it has the ρ as the correlation between two dimensions:
> 
> https://en.wikipedia.org/wiki/Multivariate_normal_distribution

Thanks very much!
