### ISSUE TITLE
data process problem.

### ISSUE THREAD

**Issue by BJHYZJ** [sshaoshuai/MTR#9]
When I want to process data, I meet a problem, I have used all the methods you recommended above, but nothing works. I really can't find the problem.
![image](https://user-images.githubusercontent.com/74347732/221619446-8404d00c-d600-4662-8463-fcfda1d5a2b0.png)

**Comment by sshaoshuai** [comment]
I think the error is caused by the environment, maybe you can try to re-install protobuf and tensorflow environment.

**Comment by flclain** [comment]
Maybe you are using the wrong version of the dataset.
Check if your data version is 1.1 instead of 1.0.

**Comment by sshaoshuai** [comment]
Feel free to reopen it if there are further questions.

**Comment by BJHYZJ** [comment]
> Maybe you are using the wrong version of the dataset. Check if your data version is 1.1 instead of 1.0.

I downloaded the 1.1 scenario, but when I run the data process, there is a problem that cur_data.lane.entry_lanes does not exist, is this a problem with my environment or the data?

**Comment by sshaoshuai** [comment]
I am not sure what happens, maybe you can try to use different waymo_open_dataset API versions, or you can also raise an issue in the repo of Waymo Open Dataset.

**Comment by BJHYZJ** [comment]
Thank you for your reply. I have solved this problem. After many comparisons, I find that it is still the version of the data set I downloaded. When I finally used the correct version of scenario 1.1, the program worked fine.

**Comment by twkillian** [comment]
Relevant to #83 and #27

**Comment by johnny-wang16** [comment]
Relevant to #60
